image: archlinux
shell: false
packages:
  - jdk11-openjdk
  - android-sdk-cmdline-tools-latest
  - openssl
  - git
  - curl
sources:
  - https://git.sr.ht/~captainepoch/husky
environment:
  ANDROID_SDK_ROOT: "/opt/android-sdk"
  BUILD_TOOLS: "build-tools;32.0.0"
  BUILD_PLATFORMS: "platforms;android-32"
  JAVA_HOME: "/usr/lib/jvm/default"
  PROJECT: husky/husky
triggers:
  - action: email
    condition: always
    to: ~captainepoch/ci@lists.sr.ht
tasks:
  - setup-sdk: |
      source /etc/profile
      sudo chown $USER:$USER -R ${ANDROID_HOME}
      yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
      yes | sdkmanager --sdk_root=$ANDROID_HOME --update
      yes | sdkmanager --sdk_root=$ANDROID_HOME "${BUILD_TOOLS}"
      "${BUILD_PLATFORMS}"
  - prepare-gradle: |
      cd ${PROJECT}
      chmod +x gradlew
  - check-lint: |
      cd ${PROJECT}
      ./gradlew ktlintCheck
  - tests-husky: |
      cd ${PROJECT}
      ./gradlew testHuskyStableDebugUnitTest --rerun-tasks
  - build-husky: |
      cd ${PROJECT}
      ./gradlew assembleHuskyStableRelease --rerun-tasks
